//
// Wolfenstein VR:
// This use to be a giant shared header, but I have broken it up into separate headers which are included here.  -Geeoff
//

#pragma once

#include "WL_MAIN.H"
#include "WL_GAME.H"
#include "WL_PLAY.H"
#include "WL_INTER.H"
#include "WL_DEBUG.H"
#include "WL_DRAW.H"
#include "WL_STATE.H"
#include "WL_SCALE.H"
#include "WL_AGENT.H"
#include "WL_ACT1.H"
#include "WL_ACT2.H"
#include "WL_TEXT.H"